New feature: Terminate when inactive
PaulStovell/ServiceBouncer pull request #46
Opened 2019-08-23 19:01 UTC by johnwalters

## What Changed?
New feature added: Terminate when inactive
If the 'terminateMinutes' option is specified, the app will terminate in the specified minutes of non-user activity.

## Screenshots

![serviceBouncerFeatureAppTerminate](https://user-images.githubusercontent.com/729200/63616464-73ce9800-c59c-11e9-9697-64ee1343204d.jpg)

## Issues Closed
#44, submitted by @chrisedebo

2019-08-23 19:36 UTC, BlythMeister commented
Thanks for the pull request.

I'm thinking that maybe should just make the auto kill always on?

2019-08-23 20:56 UTC, johnwalters commented
You are welcome for the pull request. btw it is my 1st one, ever anywhere, so I am quite open to feedback. 

Sure, I considered auto kill always on, but didn’t want to disrupt. I could default to 60, and then I’d work in a way to handle the never option on the options. 
Or we could eliminate the option and hardcode to x minutes. 
Your call.

2019-08-23 20:57 UTC, BlythMeister commented
I think hard code (at least for now) 🙂

2019-08-23 21:00 UTC, johnwalters commented
k I'm on it. 
like a hobo on a hotdog.

2019-08-23 21:18 UTC, johnwalters commented
## What Changed?
New feature added: Terminate when inactive
Now the app will terminate in 60 minutes of non-user activity.

## Screenshots

![serviceBouncerFeatureAppTerminate2](https://user-images.githubusercontent.com/729200/63624235-a3879b00-c5b0-11e9-9059-c5204dabaecc.jpg)

## Issues Closed
#44, submitted by @chrisedebo

2019-08-23 22:10 UTC, caioproiete commented
This is nice. Thanks @johnwalters !

A couple of thoughts / possible improvements either for this PR or for a future PR:

---

**1.** The approach used here to determine inactivity is by measuring active interaction with the ServiceBouncer app specifically, and not inactivity of the user in the server. So if the user is busy interacting with another app on the server for more than the X minutes defined in ServiceBouncer, it will close when the user is technically _not_ inactive, which is not a great experience IMO...

 Maybe we could look into ways of determining inactivity of the user via Windows' [`GetLastInputInfo`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getlastinputinfo) API?

Or perhaps by checking:

* Time elapsed since the user disconnected from the RDP session on the server
* Time elapsed since the user locked his screen
* (what else?)

---

**2.** Minor nitpick: Maybe we could use a `timespan` (e.g. `01:00:00`) instead of an `int` that represents minutes, to allow for more flexibility? Of course, this requires an adjustment on the timer tick interval

2019-08-24 00:06 UTC, johnwalters commented
@caioproiete You're welcome. On item 2, which int are you referring to?

2019-08-24 20:01 UTC, caioproiete commented
@johnwalters Ah! My bad. On the PR diff it shows a [change on Program.cs](https://github.com/PaulStovell/ServiceBouncer/pull/46/files#diff-98bbc2dda4856f429bff68cfc147fb14) which has some code to parse command-line arguments, and I assumed you were getting the X minutes of inactivity as a command-line argument (with a default of 60 minutes) - i.e. `ServiceBouncer.exe 90`.

I just re-read the diff and I saw no new arguments are expected and it's hard-coded to 60 minutes, so ignore item 2.

2019-08-24 20:18 UTC, johnwalters commented
OK. re: item #1, I am open to implementing what's decided on, but I feel like more discussion is needed to nail down requirements, and I don't have anything to add to that discussion.

2019-08-24 20:24 UTC, BlythMeister commented
I think we could do 30 minutes after session switch shows machine is locked.
So if you lock a machine for 30 minutes, the app will terminate.
But if you unlock after 25, then the timer starts again (even if you don't use Service Bouncer.

2019-08-26 15:10 UTC, augustoproiete commented
@BlythMeister +1

We [already hook into SessionSwitch](https://github.com/PaulStovell/ServiceBouncer/blob/master/src/ServiceBouncer/MainForm.cs#L54-L64) to determine if the machine is locked or not. Seems like the right place to start/stop a timer that closes the app after 30 minutes.

2019-08-26 19:59 UTC, johnwalters commented
I'll take a stab at implementing it. My understanding of the requirements: If the connected machine is locked and has been locked for 30 or more minutes, the app will terminate.

2019-08-26 20:49 UTC, johnwalters commented
After having a look, I think I got that wrong. Let me try again with my understanding of the requirements: If the machine on which the application is running, is locked and has been locked for 30 or more minutes, the app will terminate.
Is that correct?

2019-08-26 21:02 UTC, BlythMeister commented
Yes that is correct 🙂

2019-08-26 21:06 UTC, augustoproiete commented
> If the machine on which the application is running, is locked and has been locked for 30 or more minutes, the app will terminate

@johnwalters That's correct, but it's not just if the session is locked, but also if the user has disconnected from the remote session. Either of these would be valid.

At first glance it seems you'd have to add some code to the [`SessionSwitch` event handler](https://github.com/PaulStovell/ServiceBouncer/blob/master/src/ServiceBouncer/MainForm.cs#L54) to check the `Reason` why the session switch event was raised.

* If the reason is `SessionLock` or `RemoteDisconnect`, we consider the user is **inactive**, so we start counting the time from that moment onwards. And 30 minutes from that initial time, the app closes itself.

* If the reason is `SessionUnlock` or `RemoteConnect`, the user is back so we consider the user **active**, and stop counting the time, and the app won't close itself anymore. The next time the user locks the session or disconnects from the remote session, the above will happen again and everything starts over...

ps: When receiving a `RemoteDisconnect`, we should check if we already were counting the time due to a `SessionLock` that happened moments before, so that we don't reset the counter and lose the time in between these events.

2019-08-26 21:09 UTC, BlythMeister commented
If you have an inactive stopwatch.
When setting isactive to true, stop and reset, when setting to false start it.
When that stopwatch hits 30 minutes, kill the app.

2019-08-26 21:31 UTC, johnwalters commented
the class variable isActive is used not only when the session state changes, but also when the form is activated or deactivated, meaning when the user clicks on another app on the same box as this app or back onto this app. So I don't think that is what we want, is it? I'll try again:
1)  If the machine on which the application is running, is (locked or remotely disconnected) and has been (locked or remotely disconnected) for 30 or more minutes, the app will terminate.
That makes sense to me. Is that correct?

2019-08-26 23:05 UTC, augustoproiete commented
> If the machine on which the application is running, is (locked or remotely disconnected) and has been (locked or remotely disconnected) for 30 or more minutes, the app will terminate.

Yup. That's it. The requirements remain the same. @BlythMeister was just suggesting a possible approach to implement that... Which from your observation, doesn't look like it's a fit.

2019-08-27 17:03 UTC, johnwalters commented
## What Changed?
New feature added: Terminate when inactive
Now the app will terminate if machine on which the app is running is either locked or remotely disconnected, and 30 or more minutes have passed.

## Screenshots
(no UI change)

## Issues Closed
#44, submitted by @chrisedebo

2019-08-27 17:41 UTC, BlythMeister requested changes
A few changes and a few files that shouldn't be in the or at all as they are the same

2019-08-27 17:41 UTC, BlythMeister commented on README.md
> +As a developer building Windows Services, the workflow of constantly stopping and starting services can be a bit annoying, especially if your solution consists of multiple services. **ServiceBouncer*
I can't see the differences in this file

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +        private System.Windows.Forms.Timer appTerminationTimer = new System.Windows.Forms.Timer();
Could you use System.Threading.Timer instead

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +            appTerminationTimer.Interval = 60000;
When setting an interval in milliseconds, use Timespan.FromMinutes(1).TotalMilliseconds.
Or FromSeconds etc as this is clearer when reading what the value is without needing to do maths.

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +                var backgroundRefreshTimeText = backgroundRefreshSeconds == 1 ? "1 second" : $"{backgroundRefreshSeconds} seconds";
Can't see the differences in this or the above line

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +        private int inactivityMinutesUntilAppTermination = 30;
If you make this a timespan it make the checking easier.  You can say is this timespan bigger that other timespan.

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +            // Check to see if machine has been in an inactive state for inactivityMinutesUntilAppTermination
You don't really need this comment, the function is clear enough without it.

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +            if (minutesSinceInactivated > inactivityMinutesUntilAppTermination)
This if becomes different if using timespans

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +                Process.GetCurrentProcess().Kill();
You should use Application.Exit as it's a nicer kill 🤣

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/Program.cs
> +namespace ServiceBouncer
Can't see any difference here...

2019-08-27 17:41 UTC, BlythMeister commented on src/ServiceBouncer/ServiceBouncer.csproj
> +<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Another file which doesn't need to be here as the same.

2019-08-27 22:42 UTC, augustoproiete commented on src/ServiceBouncer/MainForm.cs
> +                    machineInactivatedTime = DateTime.Now;
You could schedule the timer here, for `machineInactivatedTime + 30 minutes`, that way you don't have to run the timer every single minute to check the inactive time.

2019-08-27 22:42 UTC, augustoproiete commented on src/ServiceBouncer/MainForm.cs
> +                machineInactivatedTime = null;
You could disable the timer here, and it will not run until a new session switch happens again

2019-08-28 04:33 UTC, BlythMeister commented on src/ServiceBouncer/MainForm.cs
> +                    machineInactivatedTime = DateTime.Now;
Yeah, that's a nice approach

2019-08-29 00:27 UTC, johnwalters commented
ok please have a look.

2019-08-29 04:32 UTC, BlythMeister approved these changes
Very nice thank you.

2019-08-29 04:33 UTC, merged

2019-08-29 07:07 UTC, johnwalters commented
Thanks for the help guys.

2019-08-29 07:11 UTC, BlythMeister commented
No worries, thanks for the changes.
I'll try and get a release out today

2019-09-10 08:51 UTC, chrisedebo commented
Hooray! 

Thanks for adding my feature request.

Good work chaps :)